################################################################################

# Copyright (c) 2022, 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)

# Copyright (c) 2022, 2023 ZF Friedrichshafen AG

# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation

#

# See the NOTICE file(s) distributed with this work for additional

# information regarding copyright ownership.

#

# This program and the accompanying materials are made available under the

# terms of the Apache License, Version 2.0 which is available at

# https://www.apache.org/licenses/LICENSE-2.0.

#

# Unless required by applicable law or agreed to in writing, software

# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT

# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the

# License for the specific language governing permissions and limitations

# under the License.

#

# SPDX-License-Identifier: Apache-2.0

################################################################################



feign:

  irsApi:

    url: http://127.0.0.1:2620

  registryApi:

    url: http://localhost:24234

  portalApi:

    url: https://portal-backend.dev.demo.catena-x.net/api



edc:

  callback-urls: http://tracex-irs:8181/internal/endpoint-data-reference



###############################################################



traceability:

  bpn: BPN20000000OCM0B

  url: http://localhost:2020

  registry.manufacturerIdKey: manufacturerId



server:

  port: 2020

  servlet:

    context-path: /api



spring:

  main:

    allow-bean-definition-overriding: true

  datasource:

    url: jdbc:postgresql://localhost:5432/trace

    username: keycloak

    password: keycloak

  security:

    oauth2:

      client:

        registration:

          keycloak:

            authorization-grant-type: client_credentials

            client-id: catenax-portal

            client-secret: 3kpM6Stf8yzfPNy7SUAENuLnKCSlgvUX

          OKTA:

            client-id: catenax-portal

            client-secret: 3kpM6Stf8yzfPNy7SUAENuLnKCSlgvUX

            authorization-grant-type: client_credentials

            scope: openid

        provider:

          keycloak:

            token-uri: http://localhost:8000/realms/catenax-ndi/protocol/openid-connect/token

          OKTA:

            token-uri: http://localhost:8000/realms/catenax-ndi/protocol/openid-connect/token

      resourceserver:

        jwt:

          jwk-set-uri: http://localhost:8000/realms/catenax-ndi/protocol/openid-connect/certs





jwt:

  resource-client: "dev-Test" #${JWT_RESOURCE_CLIENT}
